services:
  - type: web
    name: flask-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: JWT_SECRET_KEY
        value: your_secret_key
      - key: PYTHON_VERSION
        value: 3.10